[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
tuktuk = "tukpKuBbnQwG6yQbYRbeDM9Dk3D9fDkUpc6sytJsyGC"

[workspace]
members = [
  "programs/tuktuk"
]

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.test.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 20000
