name: solana-transaction-utils

on:
  push:
    branches: [main]
    tags: ['solana-transaction-utils-v*']
    paths: ['solana-transaction-utils/**', '.github/workflows/solana-transaction-utils.yml']
  pull_request:
    branches: [main]
    paths: ['solana-transaction-utils/**', '.github/workflows/solana-transaction-utils.yml']

jobs: 
  hygiene:
    runs-on: ubuntu-latest

    steps:
      - name: Setup | Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Setup | Checkout
        uses: actions/checkout@v4

      - name: Setup | Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Setup | Tools
        run: sudo apt-get install -y protobuf-compiler

      - name: Build | Hygiene
        run: |
          cargo fmt --package solana-transaction-utils -- --check
          cargo clippy --package solana-transaction-utils --all-features -- -D clippy::all

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup | Tarpaulin
        uses: jaxxstorm/action-install-gh-release@v1.12.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo: xd009642/tarpaulin

      - name: Setup | Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup | Tools
        run: sudo apt-get install -y protobuf-compiler

      - name: Test | Run
        env:
          RUST_BACKTRACE: 1
        run: |
          cargo tarpaulin --packages solana-transaction-utils --no-dead-code --engine llvm --out xml -- --test-threads 1
